version: "3.9"

services:
 backend:
  build: .
  container_name: devops-backend
  ports:
    - "3000:3000"
  environment:
    - DB_HOST=database
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_NAME=devopsdb
  depends_on:
    database:
      condition: service_healthy
  networks:
    - devops-network

  database:
    image: postgres:15
    container_name: devops-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devopsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:

networks:
  devops-network: