services:
  backend:
    build: .
    container_name: devops-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=devopsdb
    depends_on:
      - database
    networks:
      - devops-network

  database:
    image: postgres:15
    container_name: devops-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devopsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devops-network
  nginx:
    image: nginx:latest
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - devops-network

volumes:
  postgres-data:

networks:
  devops-network: